Repository GSculerlor/JikanKt, pull requests merged in 2020-05, with the labels that each got.

#11 Add characters and people search endpoints
  README.md
  build.gradle.kts
  src/main/kotlin/moe/ganen/jikankt/JikanClient.kt
  src/main/kotlin/moe/ganen/jikankt/JikanKt.kt
  src/main/kotlin/moe/ganen/jikankt/models/base/types/CharacterSearchSubEntity.kt
  src/main/kotlin/moe/ganen/jikankt/models/base/types/PeopleSearchSubEntity.kt
  src/main/kotlin/moe/ganen/jikankt/models/search/CharacterSearchResult.kt
  src/main/kotlin/moe/ganen/jikankt/models/search/PeopleSearchResult.kt
  src/test/kotlin/moe/ganen/jikankt/ExampleClass.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSearch.kt
Labels: enhancement

#12 Better exception handing
  src/main/kotlin/moe/ganen/jikankt/JikanKt.kt
  src/main/kotlin/moe/ganen/jikankt/connection/RestClient.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSearch.kt
Labels: code quality, enhancement

#15 Unit tests
  .github/release-drafter.yml
  .github/workflows/master-build.yml
  .github/workflows/pull-request.yml
  src/main/kotlin/moe/ganen/jikankt/JikanKt.kt
  src/main/kotlin/moe/ganen/jikankt/models/base/types/AnimeListEntity.kt
  src/main/kotlin/moe/ganen/jikankt/models/base/types/Episode.kt
  src/main/kotlin/moe/ganen/jikankt/models/search/AnimeSearchQuery.kt
  src/main/kotlin/moe/ganen/jikankt/models/search/MangaSearchQuery.kt
  src/main/kotlin/moe/ganen/jikankt/models/search/enums/Type.kt
  src/main/kotlin/moe/ganen/jikankt/models/season/Season.kt
  src/main/kotlin/moe/ganen/jikankt/models/user/User.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseAnime.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseCharacter.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseClub.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseGenre.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseMagazine.kt
  src/test/kotlin/moe/ganen/jikankt/TestCasePerson.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseProducer.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSchedule.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSearch.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSeason.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseTop.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseUser.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseUserLists.kt
Labels: bug, code quality, enhancement

#16 Add manga endpoints
  README.md
  build.gradle.kts
  src/main/kotlin/moe/ganen/jikankt/JikanClient.kt
  src/main/kotlin/moe/ganen/jikankt/JikanKt.kt
  src/main/kotlin/moe/ganen/jikankt/models/anime/Anime.kt
  src/main/kotlin/moe/ganen/jikankt/models/anime/MangaCharacters.kt
  src/main/kotlin/moe/ganen/jikankt/models/base/types/RelatedManga.kt
  src/main/kotlin/moe/ganen/jikankt/models/manga/Manga.kt
  src/main/kotlin/moe/ganen/jikankt/models/manga/MangaNews.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseGenre.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseManga.kt
Labels: enhancement

#18 Changed logger implementation to be and actual api logger
  build.gradle.kts
  gradle.properties
  src/main/kotlin/moe/ganen/jikankt/JikanClient.kt
  src/main/kotlin/moe/ganen/jikankt/JikanKt.kt
  src/main/kotlin/moe/ganen/jikankt/connection/RestClient.kt
  src/main/kotlin/moe/ganen/jikankt/utils/JikanLogger.kt
  src/main/kotlin/moe/ganen/jikankt/utils/SimpleLogger.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseAnime.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseGenre.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseManga.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseSearch.kt
  src/test/kotlin/moe/ganen/jikankt/TestCaseTop.kt
Labels: enhancement
